affected_purls:
- pkg:pypi/python-glanceclient@0.1.1
- pkg:pypi/python-glanceclient@0.11.0
- pkg:pypi/python-glanceclient@0.2.0
- pkg:pypi/python-glanceclient@0.3.0
- pkg:pypi/python-glanceclient@0.4.0
- pkg:pypi/python-glanceclient@0.4.1
- pkg:pypi/python-glanceclient@0.4.2
- pkg:pypi/python-glanceclient@0.5.0
- pkg:pypi/python-glanceclient@0.5.1
- pkg:pypi/python-glanceclient@0.6.0
- pkg:pypi/python-glanceclient@0.7.0
- pkg:pypi/python-glanceclient@0.8.0
- pkg:pypi/python-glanceclient@0.9.0
aliases:
- CVE-2013-4111
- GHSA-qgfg-gvff-523v
fixed_purl:
- pkg:deb/debian/python-glanceclient@1:0.9.0-2?distro=sid
- pkg:deb/debian/python-glanceclient@1:2.13.1-1?distro=sid
- pkg:deb/debian/python-glanceclient@1:3.2.2-2?distro=sid
- pkg:deb/debian/python-glanceclient@1:4.1.0-2?distro=sid
- pkg:pypi/python-glanceclient@0.10.0
references:
- id: 135454
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-updates/2013-08/msg00019.html
- id: 135455
  reference_id: ''
  url: http://rhn.redhat.com/errata/RHSA-2013-1200.html
- id: 135457
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2013:1200
- id: 135452
  reference_id: ''
  url: https://bugs.launchpad.net/ossa/+bug/1192229
- id: 177103
  reference_id: ''
  url: https://bugs.launchpad.net/python-glanceclient/+bug/1192229
- id: 135459
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=989738
- id: 177102
  reference_id: ''
  url: http://seclists.org/oss-sec/2013/q3/248
- id: 135453
  reference_id: ''
  url: https://github.com/openstack/python-glanceclient/blob/master/doc/source/index.rst
- id: 177104
  reference_id: ''
  url: https://github.com/openstack/python-glanceclient/commit/822cd6
- id: 135456
  reference_id: ''
  url: http://www.ubuntu.com/usn/USN-2004-1
- id: 125081
  reference_id: '718282'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=718282
- id: 135458
  reference_id: CVE-2013-4111
  url: https://access.redhat.com/security/cve/CVE-2013-4111
- id: 135451
  reference_id: CVE-2013-4111
  url: https://nvd.nist.gov/vuln/detail/CVE-2013-4111
- id: 135460
  reference_id: GHSA-qgfg-gvff-523v
  url: https://github.com/advisories/GHSA-qgfg-gvff-523v
severities:
- id: 18619
  reference_id: 135460
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: The Python client library for Glance (python-glanceclient) before 0.10.0
  does not properly check the preverify_ok value, which prevents the server hostname
  from being verified with a domain name in the subject's Common Name (CN) or subjectAltName
  field of the X.509 certificate and allows man-in-the-middle attackers to spoof SSL
  servers via an arbitrary valid certificate.
vulnerability_id: VCID-rr9w-q111-aaae
weaknesses: []
