affected_purls:
- pkg:deb/debian/python-pip@18.1-5
- pkg:pypi/pip@0.2
- pkg:pypi/pip@0.2.1
- pkg:pypi/pip@0.3
- pkg:pypi/pip@0.3.1
- pkg:pypi/pip@0.4
- pkg:pypi/pip@0.5
- pkg:pypi/pip@0.5.1
- pkg:pypi/pip@0.6
- pkg:pypi/pip@0.6.1
- pkg:pypi/pip@0.6.2
- pkg:pypi/pip@0.6.3
- pkg:pypi/pip@0.7
- pkg:pypi/pip@0.7.1
- pkg:pypi/pip@0.7.2
- pkg:pypi/pip@0.8
- pkg:pypi/pip@0.8.1
- pkg:pypi/pip@0.8.2
- pkg:pypi/pip@0.8.3
- pkg:pypi/pip@1.0
- pkg:pypi/pip@10.0.0
- pkg:pypi/pip@10.0.0b1
- pkg:pypi/pip@10.0.0b2
- pkg:pypi/pip@10.0.1
- pkg:pypi/pip@1.0.1
- pkg:pypi/pip@1.0.2
- pkg:pypi/pip@1.1
- pkg:pypi/pip@1.2
- pkg:pypi/pip@1.2.1
- pkg:pypi/pip@1.3
- pkg:pypi/pip@1.3.1
- pkg:pypi/pip@1.4
- pkg:pypi/pip@1.4.1
- pkg:pypi/pip@1.5
- pkg:pypi/pip@1.5.1
- pkg:pypi/pip@1.5.2
- pkg:pypi/pip@1.5.3
- pkg:pypi/pip@1.5.4
- pkg:pypi/pip@1.5.5
- pkg:pypi/pip@1.5.6
- pkg:pypi/pip@18.0
- pkg:pypi/pip@18.1
- pkg:pypi/pip@19.0
- pkg:pypi/pip@19.0.1
- pkg:pypi/pip@19.0.2
- pkg:pypi/pip@19.0.3
- pkg:pypi/pip@19.1
- pkg:pypi/pip@19.1.1
- pkg:pypi/pip@19.2
- pkg:pypi/pip@19.2.1
- pkg:pypi/pip@19.2.2
- pkg:pypi/pip@19.2.3
- pkg:pypi/pip@19.3
- pkg:pypi/pip@19.3.1
- pkg:pypi/pip@20.0
- pkg:pypi/pip@20.0.1
- pkg:pypi/pip@20.0.2
- pkg:pypi/pip@20.1
- pkg:pypi/pip@20.1.1
- pkg:pypi/pip@20.1b1
- pkg:pypi/pip@20.2
- pkg:pypi/pip@20.2.1
- pkg:pypi/pip@20.2.2
- pkg:pypi/pip@20.2.3
- pkg:pypi/pip@20.2.4
- pkg:pypi/pip@20.2b1
- pkg:pypi/pip@20.3
- pkg:pypi/pip@20.3.1
- pkg:pypi/pip@20.3.2
- pkg:pypi/pip@20.3.3
- pkg:pypi/pip@20.3.4
- pkg:pypi/pip@20.3b1
- pkg:pypi/pip@21.0
- pkg:pypi/pip@21.0.1
- pkg:pypi/pip@6.0
- pkg:pypi/pip@6.0.1
- pkg:pypi/pip@6.0.2
- pkg:pypi/pip@6.0.3
- pkg:pypi/pip@6.0.4
- pkg:pypi/pip@6.0.5
- pkg:pypi/pip@6.0.6
- pkg:pypi/pip@6.0.7
- pkg:pypi/pip@6.0.8
- pkg:pypi/pip@6.1.0
- pkg:pypi/pip@6.1.1
- pkg:pypi/pip@7.0.0
- pkg:pypi/pip@7.0.1
- pkg:pypi/pip@7.0.2
- pkg:pypi/pip@7.0.3
- pkg:pypi/pip@7.1.0
- pkg:pypi/pip@7.1.1
- pkg:pypi/pip@7.1.2
- pkg:pypi/pip@8.0.0
- pkg:pypi/pip@8.0.1
- pkg:pypi/pip@8.0.2
- pkg:pypi/pip@8.0.3
- pkg:pypi/pip@8.1.0
- pkg:pypi/pip@8.1.1
- pkg:pypi/pip@8.1.2
- pkg:pypi/pip@9.0.0
- pkg:pypi/pip@9.0.1
- pkg:pypi/pip@9.0.2
- pkg:pypi/pip@9.0.3
aliases:
- CVE-2021-3572
- GHSA-5xp3-jfq3-5q8x
fixed_purl:
- pkg:deb/debian/python-pip@20.3.4-4%2Bdeb11u1
- pkg:pypi/pip@21.1
references:
- id: 161762
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2021:3254
- id: 161763
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1962856
- id: 161761
  reference_id: ''
  url: https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b
- id: 161760
  reference_id: ''
  url: https://github.com/pypa/pip/pull/9827
- id: 161764
  reference_id: ''
  url: https://packetstormsecurity.com/files/162712/USN-4961-1.txt
- id: 134611
  reference_id: ''
  url: https://www.oracle.com/security-alerts/cpuapr2022.html
- id: 138518
  reference_id: ''
  url: https://www.oracle.com/security-alerts/cpujul2022.html
- id: 161759
  reference_id: CVE-2021-3572
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-3572
- id: 161765
  reference_id: GHSA-5xp3-jfq3-5q8x
  url: https://github.com/advisories/GHSA-5xp3-jfq3-5q8x
severities:
- id: 23874
  reference_id: 161765
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: A flaw was found in python-pip in the way it handled Unicode separators in
  git references. A remote attacker could possibly use this issue to install a different
  revision on a repository. The highest threat from this vulnerability is to data
  integrity. This is fixed in python-pip version 21.1.
vulnerability_id: VCID-jb53-jm8x-aaag
weaknesses: []
