affected_purls:
- pkg:pypi/asyncssh@0.8.1
- pkg:pypi/asyncssh@0.8.2
- pkg:pypi/asyncssh@0.8.3
- pkg:pypi/asyncssh@0.8.4
- pkg:pypi/asyncssh@0.9.0
- pkg:pypi/asyncssh@0.9.1
- pkg:pypi/asyncssh@0.9.2
- pkg:pypi/asyncssh@1.0.0
- pkg:pypi/asyncssh@1.0.1
- pkg:pypi/asyncssh@1.1.0
- pkg:pypi/asyncssh@1.10.0
- pkg:pypi/asyncssh@1.10.1
- pkg:pypi/asyncssh@1.1.1
- pkg:pypi/asyncssh@1.11.0
- pkg:pypi/asyncssh@1.11.1
- pkg:pypi/asyncssh@1.12.0
- pkg:pypi/asyncssh@1.2.0
- pkg:pypi/asyncssh@1.2.1
- pkg:pypi/asyncssh@1.3.0
- pkg:pypi/asyncssh@1.3.1
- pkg:pypi/asyncssh@1.3.2
- pkg:pypi/asyncssh@1.4.0
- pkg:pypi/asyncssh@1.4.1
- pkg:pypi/asyncssh@1.5.0
- pkg:pypi/asyncssh@1.5.1
- pkg:pypi/asyncssh@1.5.2
- pkg:pypi/asyncssh@1.5.3
- pkg:pypi/asyncssh@1.5.4
- pkg:pypi/asyncssh@1.5.5
- pkg:pypi/asyncssh@1.5.6
- pkg:pypi/asyncssh@1.6.0
- pkg:pypi/asyncssh@1.6.1
- pkg:pypi/asyncssh@1.6.2
- pkg:pypi/asyncssh@1.7.1
- pkg:pypi/asyncssh@1.7.2
- pkg:pypi/asyncssh@1.7.3
- pkg:pypi/asyncssh@1.8.0
- pkg:pypi/asyncssh@1.8.1
- pkg:pypi/asyncssh@1.9.0
aliases:
- CVE-2018-7749
fixed_purl:
- pkg:deb/debian/python-asyncssh@1.12.1-1?distro=sid
- pkg:deb/debian/python-asyncssh@1.12.2-1?distro=sid
- pkg:deb/debian/python-asyncssh@2.10.1-2?distro=sid
- pkg:deb/debian/python-asyncssh@2.5.0-0.1?distro=sid
- pkg:pypi/asyncssh@1.12.1
references:
- id: 182055
  reference_id: ''
  url: https://groups.google.com/forum/#!msg/asyncssh-announce/57_5O7kiHSA/8BXZ_hxHAQAJ
- id: 128336
  reference_id: '892787'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892787
- id: 182054
  reference_id: CVE-2018-7749
  url: https://nvd.nist.gov/vuln/detail/CVE-2018-7749
severities: []
summary: The SSH server implementation of AsyncSSH before 1.12.1 does not properly
  check whether authentication is completed before processing other requests. A customized
  SSH client can simply skip the authentication step.
vulnerability_id: VCID-vb4j-j441-aaar
weaknesses: []
