affected_purls:
- pkg:pypi/babel@0.9.6
- pkg:pypi/babel@1.0
- pkg:pypi/babel@1.1
- pkg:pypi/babel@1.2
- pkg:pypi/babel@1.3
- pkg:pypi/babel@2.0
- pkg:pypi/babel@2.1.1
- pkg:pypi/babel@2.2.0
- pkg:pypi/babel@2.3.0
- pkg:pypi/babel@2.3.1
- pkg:pypi/babel@2.3.2
- pkg:pypi/babel@2.3.3
- pkg:pypi/babel@2.3.4
- pkg:pypi/babel@2.4.0
- pkg:pypi/babel@2.5.0
- pkg:pypi/babel@2.5.1
- pkg:pypi/babel@2.5.2
- pkg:pypi/babel@2.5.3
- pkg:pypi/babel@2.6.0
- pkg:pypi/babel@2.7.0
- pkg:pypi/babel@2.8.0
- pkg:pypi/babel@2.8.1
- pkg:pypi/babel@2.9.0
aliases:
- CVE-2021-42771
- GHSA-h4m5-qpfp-3mpv
fixed_purl:
- pkg:deb/debian/python-babel@2.10.3-1?distro=sid
- pkg:deb/debian/python-babel@2.6.0%2Bdfsg.1-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/python-babel@2.8.0%2Bdfsg.1-7?distro=sid
- pkg:pypi/babel@2.9.1
references:
- id: 164286
  reference_id: ''
  url: https://github.com/python-babel/babel/pull/782
- id: 164287
  reference_id: ''
  url: https://lists.debian.org/debian-lts/2021/10/msg00040.html
- id: 164289
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/10/msg00018.html
- id: 164290
  reference_id: ''
  url: https://www.debian.org/security/2021/dsa-5018
- id: 164288
  reference_id: ''
  url: https://www.tenable.com/security/research/tra-2021-14
- id: 130091
  reference_id: '987824'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987824
- id: 164285
  reference_id: CVE-2021-42771
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-42771
- id: 164291
  reference_id: GHSA-h4m5-qpfp-3mpv
  url: https://github.com/advisories/GHSA-h4m5-qpfp-3mpv
severities:
- id: 24641
  reference_id: 164291
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Babel.Locale in Babel before 2.9.1 allows attackers to load arbitrary locale
  .dat files (containing serialized Python objects) via directory traversal, leading
  to code execution.
vulnerability_id: VCID-sd2j-th2q-aaar
weaknesses: []
