affected_purls:
- pkg:pypi/opencv-contrib-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.8
- pkg:pypi/opencv-python@3.3.0.9
aliases:
- CVE-2017-1000450
- GHSA-m43c-649m-pm48
fixed_purl:
- pkg:deb/debian/opencv@3.2.0%2Bdfsg-6?distro=sid
- pkg:deb/debian/opencv@4.5.1%2Bdfsg-5?distro=sid
- pkg:deb/debian/opencv@4.6.0%2Bdfsg-12?distro=sid
- pkg:pypi/opencv-contrib-python@3.3.0.10
- pkg:pypi/opencv-python@3.3.0.10
references:
- id: 140568
  reference_id: ''
  url: https://github.com/blendin/pocs/blob/master/opencv/0.OOB_Write_FillUniColor
- id: 140566
  reference_id: ''
  url: https://github.com/opencv/opencv/issues/9723
- id: 140567
  reference_id: ''
  url: https://github.com/opencv/opencv/pull/9726/commits/c58152d94ba878b2d7d76bcac59146312199b9eb
- id: 140569
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2018/01/msg00008.html
- id: 139476
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html
- id: 139478
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html
- id: 126673
  reference_id: '886282'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886282
- id: 140565
  reference_id: CVE-2017-1000450
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-1000450
- id: 140570
  reference_id: GHSA-m43c-649m-pm48
  url: https://github.com/advisories/GHSA-m43c-649m-pm48
severities:
- id: 19441
  reference_id: 140570
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray
  do not check the input length, which can lead to integer overflow. If the image
  is from remote, may lead to remote code execution or denial of service. This affects
  Opencv 3.3 and earlier.
vulnerability_id: VCID-9mgx-gbya-aaas
weaknesses: []
