affected_purls:
- pkg:pypi/tensorflow@2.3.0
- pkg:pypi/tensorflow-cpu@2.3.0
- pkg:pypi/tensorflow-gpu@2.3.0
aliases:
- CVE-2020-15199
- GHSA-x5cp-9pcf-pp3h
fixed_purl:
- pkg:pypi/tensorflow@2.3.1
- pkg:pypi/tensorflow-cpu@2.3.1
- pkg:pypi/tensorflow-gpu@2.3.1
references:
- id: 151605
  reference_id: ''
  url: https://github.com/tensorflow/tensorflow/commit/3cbb917b4714766030b28eba9fb41bb97ce9ee02
- id: 151583
  reference_id: ''
  url: https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1
- id: 151615
  reference_id: CVE-2020-15199
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-15199
- id: 151616
  reference_id: GHSA-x5cp-9pcf-pp3h
  url: https://github.com/advisories/GHSA-x5cp-9pcf-pp3h
- id: 151614
  reference_id: GHSA-x5cp-9pcf-pp3h
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-x5cp-9pcf-pp3h
severities:
- id: 21546
  reference_id: 151616
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 21545
  reference_id: 151614
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Denial of Service in Tensorflow
vulnerability_id: VCID-e1d6-2mea-aaan
weaknesses: []
