affected_purls:
- pkg:gem/rugged@0.0.1
- pkg:gem/rugged@0.1.0
- pkg:gem/rugged@0.1.1
- pkg:gem/rugged@0.1.2
- pkg:gem/rugged@0.16.0
- pkg:gem/rugged@0.16.0b1
- pkg:gem/rugged@0.17.0b1
- pkg:gem/rugged@0.17.0b2
- pkg:gem/rugged@0.17.0.b6
- pkg:gem/rugged@0.17.0.b7
- pkg:gem/rugged@0.18.0.b1
- pkg:gem/rugged@0.18.0.gh.de28323
- pkg:gem/rugged@0.19.0
- pkg:gem/rugged@0.21.0
- pkg:gem/rugged@0.21.1b0
- pkg:gem/rugged@0.21.1b1
- pkg:gem/rugged@0.21.1b2
- pkg:gem/rugged@0.21.2
- pkg:gem/rugged@0.21.3
- pkg:gem/rugged@0.21.4
- pkg:gem/rugged@0.22.0b1
- pkg:gem/rugged@0.22.0b2
- pkg:gem/rugged@0.22.0b3
- pkg:gem/rugged@0.22.0b4
- pkg:gem/rugged@0.22.0b5
- pkg:gem/rugged@0.22.1b1
- pkg:gem/rugged@0.22.2
- pkg:gem/rugged@0.23.0
- pkg:gem/rugged@0.23.0b1
- pkg:gem/rugged@0.23.0b2
- pkg:gem/rugged@0.23.0b4
- pkg:gem/rugged@0.23.1
- pkg:gem/rugged@0.23.1.6.g1346734.pre
- pkg:gem/rugged@0.23.2
- pkg:gem/rugged@0.23.3
- pkg:gem/rugged@0.24.0
- pkg:gem/rugged@0.24.0b0
- pkg:gem/rugged@0.24.0b11
- pkg:gem/rugged@0.24.0b12
- pkg:gem/rugged@0.24.0b13
- pkg:gem/rugged@0.24.0b14
- pkg:gem/rugged@0.24.0b2
- pkg:gem/rugged@0.24.0b3
- pkg:gem/rugged@0.24.0b4
- pkg:gem/rugged@0.24.0b5
- pkg:gem/rugged@0.24.0b6
- pkg:gem/rugged@0.24.0b7
- pkg:gem/rugged@0.24.0b8
- pkg:gem/rugged@0.24.0b9
- pkg:gem/rugged@0.24.5
- pkg:gem/rugged@0.24.6.1
- pkg:gem/rugged@0.25.0
- pkg:gem/rugged@0.25.0b1
- pkg:gem/rugged@0.25.0b10
- pkg:gem/rugged@0.25.0b2
- pkg:gem/rugged@0.25.0b3
- pkg:gem/rugged@0.25.0b4
- pkg:gem/rugged@0.25.0b5
- pkg:gem/rugged@0.25.0b6
- pkg:gem/rugged@0.25.0b7
- pkg:gem/rugged@0.25.0b8
- pkg:gem/rugged@0.25.0b9
- pkg:gem/rugged@0.25.1
- pkg:gem/rugged@0.25.1.1
- pkg:gem/rugged@0.26.0
- pkg:gem/rugged@0.26.0b1
- pkg:gem/rugged@0.26.0b2
- pkg:gem/rugged@0.26.0b3
- pkg:gem/rugged@0.26.0b4
- pkg:gem/rugged@0.26.0b5
- pkg:gem/rugged@0.26.3
- pkg:gem/rugged@0.27.0
- pkg:gem/rugged@0.27.1
- pkg:gem/rugged@0.27.2
- pkg:pypi/pygit2@0.16.0
- pkg:pypi/pygit2@0.16.1
- pkg:pypi/pygit2@0.16.2
- pkg:pypi/pygit2@0.17.0
- pkg:pypi/pygit2@0.17.1
- pkg:pypi/pygit2@0.17.2
- pkg:pypi/pygit2@0.17.3
- pkg:pypi/pygit2@0.18.0
- pkg:pypi/pygit2@0.18.1
- pkg:pypi/pygit2@0.19.0
- pkg:pypi/pygit2@0.19.1
- pkg:pypi/pygit2@0.20.0
- pkg:pypi/pygit2@0.20.1
- pkg:pypi/pygit2@0.20.2
- pkg:pypi/pygit2@0.20.3
- pkg:pypi/pygit2@0.21.0
- pkg:pypi/pygit2@0.21.1
- pkg:pypi/pygit2@0.21.2
- pkg:pypi/pygit2@0.21.3
- pkg:pypi/pygit2@0.21.4
- pkg:pypi/pygit2@0.22.0
- pkg:pypi/pygit2@0.22.1
- pkg:pypi/pygit2@0.23.0
- pkg:pypi/pygit2@0.23.1
- pkg:pypi/pygit2@0.23.2
- pkg:pypi/pygit2@0.23.3
- pkg:pypi/pygit2@0.24.0
- pkg:pypi/pygit2@0.24.1
- pkg:pypi/pygit2@0.24.2
- pkg:pypi/pygit2@0.25.0
- pkg:pypi/pygit2@0.25.1
- pkg:pypi/pygit2@0.26.0
- pkg:pypi/pygit2@0.26.1
- pkg:pypi/pygit2@0.26.2
- pkg:pypi/pygit2@0.26.3
- pkg:pypi/pygit2@0.26.4
- pkg:pypi/pygit2@0.27.0
- pkg:pypi/pygit2@0.27.1
aliases:
- CVE-2018-10888
fixed_purl:
- pkg:deb/debian/libgit2@0.27.4%2Bdfsg.1-0.1?distro=sid
- pkg:deb/debian/libgit2@0.27.7%2Bdfsg.1-0.2?distro=sid
- pkg:deb/debian/libgit2@1.1.0%2Bdfsg.1-4%2Bdeb11u1?distro=sid
- pkg:deb/debian/libgit2@1.5.1%2Bds-1?distro=sid
references:
- id: 181683
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1598024
- id: 127802
  reference_id: '903508'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903508
- id: 181682
  reference_id: CVE-2018-10888
  url: https://nvd.nist.gov/vuln/detail/CVE-2018-10888
severities: []
summary: A flaw was found in libgit2 before version 0.27.3. A missing check in git_delta_apply
  function in delta.c file, may lead to an out-of-bound read while reading a binary
  delta file. An attacker may use this flaw to cause a Denial of Service.
vulnerability_id: VCID-qcu9-nce8-aaaa
weaknesses: []
