affected_purls:
- pkg:deb/debian/python-django@0.95.1-1
- pkg:deb/debian/python-django@0.95.1-1etch2
- pkg:deb/debian/python-django@1.0.2-1%2Blenny3
- pkg:deb/debian/python-django@1.2.3-3%2Bsqueeze10
- pkg:deb/debian/python-django@1.2.3-3%2Bsqueeze15
- pkg:pypi/django@1.1.3
- pkg:pypi/django@1.2
- pkg:pypi/django@1.2.1
- pkg:pypi/django@1.2.2
- pkg:pypi/django@1.2.3
- pkg:pypi/django@1.2.4
aliases:
- CVE-2011-0696
- GHSA-5j2h-h5hg-3wf8
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@1.2.5-1?distro=sid
- pkg:deb/debian/python-django@1.4.5-1%2Bdeb7u16
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@1.1.4
- pkg:pypi/django@1.2.5
references:
- id: 133961
  reference_id: ''
  url: http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054207.html
- id: 133962
  reference_id: ''
  url: http://lists.fedoraproject.org/pipermail/package-announce/2011-February/054208.html
- id: 133963
  reference_id: ''
  url: http://openwall.com/lists/oss-security/2011/02/09/6
- id: 133959
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=676357
- id: 187186
  reference_id: ''
  url: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-0696
- id: 133964
  reference_id: ''
  url: http://secunia.com/advisories/43230
- id: 133965
  reference_id: ''
  url: http://secunia.com/advisories/43297
- id: 133966
  reference_id: ''
  url: http://secunia.com/advisories/43382
- id: 133967
  reference_id: ''
  url: http://secunia.com/advisories/43426
- id: 133968
  reference_id: ''
  url: http://www.debian.org/security/2011/dsa-2163
- id: 133969
  reference_id: ''
  url: http://www.djangoproject.com/weblog/2011/feb/08/security/
- id: 133970
  reference_id: ''
  url: http://www.mandriva.com/security/advisories?name=MDVSA-2011:031
- id: 133971
  reference_id: ''
  url: http://www.securityfocus.com/bid/46296
- id: 133972
  reference_id: ''
  url: http://www.ubuntu.com/usn/USN-1066-1
- id: 133973
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2011/0372
- id: 133974
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2011/0388
- id: 133975
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2011/0429
- id: 133976
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2011/0439
- id: 133977
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2011/0441
- id: 133958
  reference_id: CVE-2011-0696
  url: https://nvd.nist.gov/vuln/detail/CVE-2011-0696
- id: 133960
  reference_id: GHSA-5j2h-h5hg-3wf8
  url: https://github.com/advisories/GHSA-5j2h-h5hg-3wf8
severities:
- id: 18431
  reference_id: 133960
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Django 1.1.x before 1.1.4 and 1.2.x before 1.2.5 does not properly validate
  HTTP requests that contain an X-Requested-With header, which makes it easier for
  remote attackers to conduct cross-site request forgery (CSRF) attacks via forged
  AJAX requests that leverage a "combination of browser plugins and redirects," a
  related issue to CVE-2011-0447.
vulnerability_id: VCID-54j5-c7u9-aaak
weaknesses: []
