affected_purls:
- pkg:pypi/cryptography@1.8
- pkg:pypi/cryptography@1.8.1
- pkg:pypi/cryptography@1.8.2
- pkg:pypi/cryptography@1.9
- pkg:pypi/cryptography@2.0
- pkg:pypi/cryptography@2.0.1
- pkg:pypi/cryptography@2.0.2
- pkg:pypi/cryptography@2.0.3
- pkg:pypi/cryptography@2.1
- pkg:pypi/cryptography@2.1.1
- pkg:pypi/cryptography@2.1.2
- pkg:pypi/cryptography@2.1.3
- pkg:pypi/cryptography@2.1.4
- pkg:pypi/cryptography@2.2
- pkg:pypi/cryptography@2.2.1
- pkg:pypi/cryptography@2.2.2
- pkg:pypi/cryptography@2.3
- pkg:pypi/cryptography@2.3.1
- pkg:pypi/cryptography@2.4
- pkg:pypi/cryptography@2.4.1
- pkg:pypi/cryptography@2.4.2
- pkg:pypi/cryptography@2.5
- pkg:pypi/cryptography@2.6
- pkg:pypi/cryptography@2.6.1
- pkg:pypi/cryptography@2.7
- pkg:pypi/cryptography@2.8
- pkg:pypi/cryptography@2.9
- pkg:pypi/cryptography@2.9.1
- pkg:pypi/cryptography@2.9.2
- pkg:pypi/cryptography@3.0
- pkg:pypi/cryptography@3.1
- pkg:pypi/cryptography@3.1.1
- pkg:pypi/cryptography@3.2
- pkg:pypi/cryptography@3.2.1
- pkg:pypi/cryptography@3.3
- pkg:pypi/cryptography@3.3.1
- pkg:pypi/cryptography@3.3.2
- pkg:pypi/cryptography@3.4
- pkg:pypi/cryptography@3.4.1
- pkg:pypi/cryptography@3.4.2
- pkg:pypi/cryptography@3.4.3
- pkg:pypi/cryptography@3.4.4
- pkg:pypi/cryptography@3.4.5
- pkg:pypi/cryptography@3.4.6
- pkg:pypi/cryptography@3.4.7
- pkg:pypi/cryptography@3.4.8
- pkg:pypi/cryptography@35.0.0
- pkg:pypi/cryptography@36.0.0
- pkg:pypi/cryptography@36.0.1
- pkg:pypi/cryptography@36.0.2
- pkg:pypi/cryptography@37.0.0
- pkg:pypi/cryptography@37.0.1
- pkg:pypi/cryptography@37.0.2
- pkg:pypi/cryptography@37.0.3
- pkg:pypi/cryptography@37.0.4
- pkg:pypi/cryptography@38.0.0
- pkg:pypi/cryptography@38.0.1
- pkg:pypi/cryptography@38.0.2
- pkg:pypi/cryptography@38.0.3
- pkg:pypi/cryptography@38.0.4
- pkg:pypi/cryptography@39.0.0
aliases:
- CVE-2023-23931
- GHSA-w7pp-m8wf-vj6r
fixed_purl: []
references:
- id: 175028
  reference_id: ''
  url: https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3
- id: 175029
  reference_id: CVE-2023-23931
  url: https://nvd.nist.gov/vuln/detail/CVE-2023-23931
- id: 175030
  reference_id: GHSA-w7pp-m8wf-vj6r
  url: https://github.com/advisories/GHSA-w7pp-m8wf-vj6r
- id: 175027
  reference_id: GHSA-w7pp-m8wf-vj6r
  url: https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r
severities:
- id: 27581
  reference_id: 175030
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 27580
  reference_id: 175027
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Cipher.update_into can corrupt memory if passed an immutable python object
  as the outbuf
vulnerability_id: VCID-gehe-ncp5-aaaa
weaknesses: []
