affected_purls:
- pkg:pypi/mercurial@2.6.2
- pkg:pypi/mercurial@2.6.3
- pkg:pypi/mercurial@2.7.0
- pkg:pypi/mercurial@2.7.1
- pkg:pypi/mercurial@2.7.2
- pkg:pypi/mercurial@2.8
- pkg:pypi/mercurial@2.8.1
- pkg:pypi/mercurial@2.8.2
- pkg:pypi/mercurial@2.9
- pkg:pypi/mercurial@2.9.1
- pkg:pypi/mercurial@3.0
- pkg:pypi/mercurial@3.0.1
- pkg:pypi/mercurial@3.1
- pkg:pypi/mercurial@3.1.1
- pkg:pypi/mercurial@3.1.2
- pkg:pypi/mercurial@3.2
- pkg:pypi/mercurial@3.2.1
- pkg:pypi/mercurial@3.2.2
- pkg:pypi/mercurial@3.2.3
- pkg:pypi/mercurial@3.2.4
- pkg:pypi/mercurial@3.3
- pkg:pypi/mercurial@3.3.1
- pkg:pypi/mercurial@3.3.2
- pkg:pypi/mercurial@3.3.3
- pkg:pypi/mercurial@3.3-rc
- pkg:pypi/mercurial@3.4
- pkg:pypi/mercurial@3.4.1
- pkg:pypi/mercurial@3.4.2
- pkg:pypi/mercurial@3.4-rc
- pkg:pypi/mercurial@3.5
- pkg:pypi/mercurial@3.5.1
- pkg:pypi/mercurial@3.5.2
- pkg:pypi/mercurial@3.5-rc
- pkg:pypi/mercurial@3.6
- pkg:pypi/mercurial@3.6.1
- pkg:pypi/mercurial@3.6.2
- pkg:pypi/mercurial@3.6.3
- pkg:pypi/mercurial@3.6-rc
- pkg:pypi/mercurial@3.7
- pkg:pypi/mercurial@3.7.1
- pkg:pypi/mercurial@3.7.2
- pkg:pypi/mercurial@3.7.3
- pkg:pypi/mercurial@3.7-rc
- pkg:pypi/mercurial@3.8
- pkg:pypi/mercurial@3.8.1
- pkg:pypi/mercurial@3.8.2
- pkg:pypi/mercurial@3.8.3
- pkg:pypi/mercurial@3.8.4
- pkg:pypi/mercurial@3.8-rc
- pkg:pypi/mercurial@3.9
- pkg:pypi/mercurial@3.9.1
- pkg:pypi/mercurial@3.9.2
- pkg:pypi/mercurial@3.9-rc
- pkg:pypi/mercurial@4.0
- pkg:pypi/mercurial@4.0.1
- pkg:pypi/mercurial@4.0.2
- pkg:pypi/mercurial@4.0-rc
- pkg:pypi/mercurial@4.1
- pkg:pypi/mercurial@4.1.1
- pkg:pypi/mercurial@4.1.2
- pkg:pypi/mercurial@4.1-rc
aliases:
- CVE-2017-9462
- GHSA-ghjx-3jg5-h6r2
fixed_purl:
- pkg:deb/debian/mercurial@4.3.1-1?distro=sid
- pkg:deb/debian/mercurial@4.8.2-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/mercurial@5.6.1-4?distro=sid
- pkg:deb/debian/mercurial@6.3.2-1?distro=sid
- pkg:pypi/mercurial@4.1.3
references:
- id: 143042
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2017:1576
- id: 143043
  reference_id: ''
  url: https://bugs.debian.org/861243
- id: 143045
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2018/07/msg00005.html
- id: 143046
  reference_id: ''
  url: https://security.gentoo.org/glsa/201709-18
- id: 143047
  reference_id: ''
  url: https://www.mercurial-scm.org/repo/hg/rev/77eaf9539499
- id: 143048
  reference_id: ''
  url: https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.1.3_.282017-4-18.29
- id: 143049
  reference_id: ''
  url: http://www.debian.org/security/2017/dsa-3963
- id: 143050
  reference_id: ''
  url: http://www.securityfocus.com/bid/99123
- id: 127625
  reference_id: '861243'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861243
- id: 143041
  reference_id: CVE-2017-9462
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-9462
- id: 143044
  reference_id: GHSA-ghjx-3jg5-h6r2
  url: https://github.com/advisories/GHSA-ghjx-3jg5-h6r2
severities:
- id: 19938
  reference_id: 143044
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: In Mercurial before 4.1.3, "hg serve --stdio" allows remote authenticated
  users to launch the Python debugger, and consequently execute arbitrary code, by
  using --debugger as a repository name.
vulnerability_id: VCID-7ggx-1ssh-aaar
weaknesses: []
